name: functions_client
description: A dart client library for the Supabase functions.
version: 1.0.0-dev.2
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase-community/functions-dart'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.4
